#%RAML 1.0 DataType
type: object
properties:
  status: string # Response status , Success or Error/Reject
  correlationId: string # Unique transaction id
  message?: string # Response user friendly message response 