#%RAML 1.0
title: Forms Services Liveness Check
version: v1
baseUri: http://qa.api.assurant.com/api
mediaType: application/json

securitySchemes:
  basic_auth:
    description: |
      This API supports Basic Authentication.
    type: Basic Authentication

/alive:
  get:
    securedBy: [basic_auth]
    description: Liveness Check call for API.      
    responses:
      204:
        description: API is up and running.


/components/health:
  get:
    securedBy: [basic_auth]
    description: Components healthcheck call for all the API included components calls availability check.       
    responses:
      200:
        body:
          application/json:
            example:
              !include /examples/components-check-success-response-example.json          
      500:
        body:
          application/json: