mule.env=local

#http connector properties
http.private.host=0.0.0.0
http.private.port=8091
https.private.port=8092
ssl.keystore.password=9OO5VaXTProU0mykvBPj
api.forms.name.path=/experience-forms-api/*
api.forms.internal.services.name.path=/experience-forms-internal-services-api/*
api.forms.soap.implementation.path=/FormsWebServiceImplService/FormsWebServiceImplPort
api.forms.internal.name.path=/experience-forms-internal-api/*
api.forms.liveness.name.path=/experience-forms-liveness-api/*
api.forms.healthCheck.name.path=/experience-forms-healthCheck-api/*
api.document.service.id=18947654
api.document.internal.services.id=19135982
api.document.liveness.id=19796416
api.document.healthCheck.id=19796414
http.internal.connection.idletimeout=5000
http.internal.response.timeout=30000

#anypoint platform properties
anypoint.platform.platform_base_uri=https://anypoint.mulesoft.com/apiplatform
anypoint.platform.coreservice_base_uri=https://anypoint.mulesoft.com/accounts
anypoint.platform.analytics_base_uri=https://analytics-ingest.anypoint.mulesoft.com
anypoint.platform.contracts_base_uri=https://anypoint.mulesoft.com/apigateway/ccs
anypoint.platform.client_id=d838ba1ae21d4a2394d45e4666c9e2de
anypoint.platform.client_secret=

#VIN Decode properties
api.vehicle.http.internal.listener.host=mule-worker-internal-m4-quoting-support-services-dev.us-e1.cloudhub.io
api.vehicle.http.internal.listener.port=8091
api.userDetails.internal.listener.path=/experience-internal-vehicle-api/user/details
api.getVehicleDetails.internal.listener.path=/experience-internal-qcert-api/vehicleDetails
api.updateInventoryDetails.internal.listener.path=/experience-internal-qcert-api/updateInventoryDetails
api.vehicle.http.internal.connection.idletimeout=${http.internal.connection.idletimeout}
api.vehicle.http.internal.response.timeout=${http.internal.response.timeout}

#Logger DB Details:
-------------------
db.integration.logger.mssql.host=usz19dinfdb01.twg.warranty.local
db.integration.logger.mssql.port=1433
db.integration.logger.mssql.database=Informatica_Global
db.integration.logger.mssql.user=Usr_Informatica_Global_uat
db.integration.logger.mssql.password=NUr3k6Jeapp
db.integration.logger.mssql.trustServerCertificate=true
db.integration.azure.mssql.pool.size.max=50
db.integration.azure.mssql.pool.connection.timeout=120000
db.integration.azure.mssql.pool.maxLifetime=1800000
logger.api.generic.log.table=Uat.Integration_Mule_Application_Logs
logger.api.forms.generic.log.table=Uat.Integration_Mule_Application_EFTForms_Logs
logger.api.forms.generic.log.sp=Uat.SP_INSERT_EFTFormsLogDetails
db.healthcheck.query=SELECT 1 as ID

#datasource properties
db.sql.rate.azure.host=vdbdrating.database.cead.prd
db.sql.rate.azure.database=Rating
db.sql.rate.azure.port=1433
db.sql.rate.azure.user=RatingApp-Dev
db.sql.rate.azure.password=U2nr4xwa6LARQUqs
db.sql.rate.azure.getexpirationtype=dbo.usp_Rating_GetExpirationType
db.sql.rate.azure.pool.size.max=50
db.sql.rate.azure.pool.connection.timeout=60000
db.sql.rate.azure.pool.maxLifetime=1800000
sql.reconnection.attempts=2
sql.reconnection.frequency=3000

#Salesforce connection properties

sfdc.url=https://test.salesforce.com/services/Soap/u/38.0
#sfdc.userid=mulesoftus@thewarrantygroup.com.twgqa1d
#sfdc.password=Y4RegeA4KpTA2H5k1d3

sfdc.userid=mulesoftus@assurant.com.twgqa3B
sfdc.password=mulesoft10133



##Needed for file upload
springcm.authentication.api.implementation.host=auth.springcm.com
springcm.authentication.api.implementation.path=/api/v201606/apiuser
springcm.authentication.api.client_id=657515c6-09de-427c-9e72-27603fb57284
springcm.authentication.api.client_secret=e30220e7eb4343b7974f3f04443cf78bdZnYoUidIZ4GHyCx8xD1GPBgf1WBai5Yu4DPRD5kq63lexUdcTwgOO05Kx4lmZKtvibiDBWZ1hS00eyKoyBWg0IPrmHW46zU
springcm.api.implementation.port=443
springcm.api.implementation.content=application/json
springcm.api.connection.timeout=30000
springcm.api.response.timeout=180000
springcm.authentication.parent.folderId.url=https://apina11.springcm.com/v201411/folders/5b81fc1f-88cb-ee11-9c7a-2c44fd93e385
springcm.document.generation.api.implementation.host=apina11.springcm.com
springcm.authentication.parent.hardCopyFolderId.url=https://apina11.springcm.com/v201411/folders/38de5f7e-37d0-ee11-9c7a-2c44fd93e385

#SpringCM Config
springcm.api.implementation.host=apina11.springcm.com
springcm.api.implementation.port=443
springcm.folder.upload.api.implementation.path=/v201411/folders
springcm.api.connection.timeout=30000
springcm.api.response.timeout=180000

springcm.document.upload.api.implementation.host=apiuploadna11.springcm.com
springcm.document.upload.api.implementation.path=v201411/folders/[folderId]/documents
springcm.api.until.successful.max.retry=3
springcm.api.until.successful.retry.interval=5000
springcm.api.connection.timeout=30000
springcm.api.response.timeout=180000

api.system.objectstore.partition=authTokenPartition
api.system.objectstore.ttl=3600000
api.system.objectstore.expirationtime=3600000




#Needed for template download
springcm.document.download.api.implementation.host=apidownloadna11.springcm.com
springcm.document.download.api.implementation.path=v201411/documents
springcm.document.download.retry.count=2
springcm.document.download.retry.milliseconds=10
springcm.document.upload.api.implementation.host=apiuploadna11.springcm.com
springcm.document.upload.api.implementation.path=v201411/folders/[folderId]/documents

api.template.url.objectstore.ttl=30
api.template.url.objectstore.expirationtime=45

#QR Code Configuration Properties
qr.code.flow.enable.flag=true
qr.code.implementation.protocol=HTTPS
qr.code.implementation.host=2bxoz4cgvf.execute-api.us-east-1.amazonaws.com
qr.code.implementation.port=443
qr.code.implementation.path=/invitation
qr.code.implementation.key=a53ff8cd-f21f-49b5-9787-e7b821f84d1b
qr.code.implementation.basepath=/



formsUserList=;GLOW;
exception.connection.key=Connection Exception
exception.connection.message= A connection Exception occurred. Please try again.
exception.general.key=Exception occurred
exception.general.message=A unknown exception occurred. Please try again.

#expirationType properties
api.expirationType.http.internal.listener.host=localhost
api.expirationType.http.internal.listener.port=8091
api.expirationType.http.internal.listener.path=/experience-internal-rerates-api/expirationType
api.expirationType.http.internal.connection.idletimeout=${http.internal.connection.idletimeout}
api.expirationType.http.internal.response.timeout=${http.internal.response.timeout}

#proprties for PR and ENT
classification.code.pr=PRG
springcm.authentication.parent.folderId.url=https://apina21.springcm.com/v201411/folders/5e400f35-066b-ef11-b81d-9440c99fa601
springcm.authentication.parent.ent.folderId.url=https://apina21.springcm.com/v201411/folders/c8f825ae-266b-ef11-b81d-9440c99fa601
#Abstract Generate Forms
exception.forms.number.key=dealer.internalId.invalid
exception.forms.number.message=The dealers internal Id cannot be null, blank nor contain whitespaces only.

#Service Forms
api.implementation.external.host=dev.api.assurant.com

#sfdc.userid=mulesoftus@thewarrantygroup.com.twgqa1e
#sfdc.url=https://test.salesforce.com/services/Soap/u/48.0
#sfdc.password=

#EPG Claims Attachments API
epg.claims.attachments.listener.path=/epg-claims-attachments-api/*
epg.claims.attachments.api.id=18840962

#SFTP connection properties
sftp.epg.auth.workingDir=/ToAssurantEFT
sftp.epg.auth.host=sftp1-uat.assurant.com
sftp.epg.auth.port=22
sftp.epg.auth.username=glcnh2epgm01
sftp.epg.auth.password=
sftp.epg.connect.retry.count=5
sftp.epg.connect.retry.freq=3000
wsdl.address.location.host=https://dev.api.assurant.com

#QCERT Print Sticker Configurations
org.glassfish.grizzly.http.PRESERVE_HEADER_CASE=true

##Experience Forms Template API
api.form.template.id=19282217

#cloudhub Notification Properties
cloudhub.alert.client_id=e1825de0ca32491fa510215baa2e834d
cloudhub.alert.client_secret=f8C6178CdC6749aF88Aa6077Fc1E4F75
cloudhub.alert.environment=8b6758b6-9b32-49e4-9049-c6c26a1d734c
cloudhub.alert.domain=m4-document-services-qa


#catching Strategy
cache.user.validation.size=2500
cache.user.validation.expire=86400000
cache.user.validation.ttl=86400000

#azure Key Vault properties
azure.keyvault.clientid=34438508-0cda-4e5f-9c63-75f4fd58aae1
azure.keyvault.tenantId=8654270e-8954-40b4-bc51-b1640deabccc
azure.keyvault.clientsecret=
azure.keyvault.name=MuleSoftKVdev
azure.keyvault.secret.docusign.pkey.name=MuleDocusignPKdev

#docusign properties
docusign.authentication.api.implementation.path=oauth/token
docusign.authentication.host=account-d.docusign.com
docusign.authentication.port=443
docusign.authentication.path=oauth/token
docusign.authentication.grant_type=urn:ietf:params:oauth:grant-type:jwt-bearer
docusign.accountId=e9813426-bf7d-481c-a961-47be50147e21
docusign.integrationKey=68290c4d-b729-4009-960d-cf3e1b55624e
#sub
docusign.integrationUserId=3dafbdcf-868c-4703-a00d-e527f2ed18f0
docusign.document.download.api.implementation.host=apidownloaduatna11.springcm.com
docusign.document.download.api.implementation.path=/v2/${docusign.accountId}/documents

docusign.api.implementation.host=apiuatna11.springcm.com
docusign.document.upload.api.implementation.host=apiuploaduatna11.springcm.com
docusign.document.upload.api.implementation.path=v2/${docusign.accountId}/folders/[folderId]/documents
docusign.folder.upload.api.implementation.path=/v2/${docusign.accountId}/folders/search
docusign.folder.create.api.implementation.path=/v2/${docusign.accountId}/folders
docusign.authentication.parent.folderId.url=https://apiuatna11.springcm.com/v2/${docusign.accountId}/folders/b8c47c27-4618-e911-9c1c-3ca82a1e3f41
docusign.authentication.parent.ent.folderId.url=https://apiuatna11.springcm.com/v2/${docusign.accountId}/folders/c8f825ae-266b-ef11-b81d-9440c99fa601
docusign.authentication.parent.hardCopyFolderId.url=https://apiuatna11.springcm.com/v2/${docusign.accountId}/folders/c8f825ae-266b-ef11-b81d-9440c99fa601


document.authentication.source=docusign
document.download.api.implementation.host=${docusign.document.download.api.implementation.host}
document.download.api.implementation.path=${docusign.document.download.api.implementation.path}
document.upload.api.implementation.host=${docusign.document.upload.api.implementation.host}
document.upload.api.implementation.path=${docusign.document.upload.api.implementation.path}

privatekey.object.store.entry.ttl=3600
privatekey.object.store.expiration.interval=10


document.folder.upload.api.implementation.path=${docusign.folder.upload.api.implementation.path}
document.api.implementation.host=${docusign.api.implementation.host}
document.folder.create.api.implementation.path=${docusign.folder.create.api.implementation.path}
document.authentication.parent.folderId.url=${docusign.authentication.parent.folderId.url}
document.authentication.parent.ent.folderId.url=${docusign.authentication.parent.ent.folderId.url}
document.authentication.parent.hardCopyFolderId.url=${docusign.authentication.parent.hardCopyFolderId.url}
